[package]
name = "breach"
description = "HTTP error schema."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[package.metadata.docs.rs]
all-features = true

[features]
default = ["macros"]
macros = ["dep:breach-macros"]
utoipa = ["dep:itertools", "dep:utoipa"]

[dependencies]
breach-macros = { workspace = true, optional = true }
http.workspace = true
itertools = { version = "0.14.0", optional = true }
utoipa = { workspace = true, optional = true }

[dev-dependencies]

[lints]
workspace = true
